# -*- coding: utf-8 -*-
"""Database - Q3_2020

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VO04wVaCSiEQlbrxpzLeVrMoo7KaXgAV
"""

import pandas as pd

Sales = pd.read_csv (r"/content/drive/MyDrive/Database - Q3_2020 - Sales.csv")

Sales = Sales.iloc[:9506]

Sales.columns.values[0] = "Ngày"

print(Sales.dtypes)

# Chuyển các cột ngày tháng về datetime
date_columns = ['Ngày', 'Close Date']
for col in date_columns:
    Sales[col] = pd.to_datetime(Sales[col], errors='coerce', dayfirst=True)

# Chuyển các cột số tiền về float (loại bỏ dấu phẩy nếu có)
money_columns = ['Số tiền giảm giá', 'Tổng tiền']
for col in money_columns:
    Sales[col] = Sales[col].replace({',': ''}, regex=True)  # Xóa dấu phẩy trong số tiền
    Sales[col] = pd.to_numeric(Sales[col], errors='coerce')

Sales['SĐT'] = Sales['SĐT'].astype('Int64')
Sales['Số lượng bộ sách'] = Sales['Số lượng bộ sách'].astype('Int64')
Sales['Số lần tương tác'] = Sales['Số lần tương tác'].astype('Int64')

# Kiểm tra kết quả
print(Sales.dtypes)

print(Sales.isna().sum())

Sales = pd.DataFrame(Sales)
Sales = Sales.drop(columns=["Ngày gọi", "Ngày hẹn gọi lại"])

Sales.loc[(Sales['Level'] == "L8.2 - Khách đã thanh toán toàn bộ") & (Sales['Trạng thái'].isna()), 'Trạng thái'] = "Đặt hàng"

trangthai_values = Sales["Trạng thái"].count()
level_values = Sales["Level"].count()
print(f"🔢 Tổng số giá trị trong cột 'Trạng thái':{trangthai_values} và 'Level': {level_values}")

print(Sales["Trạng thái"].isna().sum())

unique_status_level = Sales[["Trạng thái", "Level"]].drop_duplicates().reset_index(drop=True)
print(unique_status_level)

Sales.to_excel("Sales.xlsx", index=False, engine="openpyxl")

MKT = pd.read_csv (r"/content/drive/MyDrive/Database - Q3_2020 - MKT.csv")

MKT["Chi phí Marketing"] = pd.to_numeric(MKT["Chi phí Marketing"], errors='coerce').fillna(0)

# Tính tổng
total_cost = MKT["Chi phí Marketing"].sum()

print(f"Tổng chi phí marketing: {total_cost:,.2f}")

# Tính tổng Leads theo Channel
mkt_lead_by_channel = MKT.groupby('Channel')['Lead MKT'].sum().reset_index()

print(mkt_lead_by_channel)

print(MKT.dtypes)

print(MKT.isna().sum())

MKT.to_excel("MKT.xlsx", index=False, engine="openpyxl")

Vandon = pd.read_csv (r'/content/drive/MyDrive/Database - Q3_2020 - Vận đơn.csv')

print(Vandon.isna().sum())

VD = pd.DataFrame(Vandon)
VD = VD.drop(columns=["Ghi chú sản phẩm", "Serial"])

print(VD.dtypes)

VD.to_excel("Van_don.xlsx", index=False, engine="openpyxl")

